### ISSUE TITLE
[TRAD] SEO form

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#824]
Keywords (capital K)
Language (full word and capital L)
Robots (capital R)

**Comment by mickaelandrieu** [comment]
hmm this is not realy possible.

I will explain how the SEO form is build and then we can discuss on a pragmmatic solution.


To build the SEO form, we use the real page metadata:

```html
<head>
    <meta name="keywords" content="cms, content manager" />
    <meta name="description" content="backbee demo website" lang="en" />
    <meta name="robots" content="" />
</head>
```

This fields come from the SEO configuration of BackBee CMS file:

```yaml
// repository/Config/metadata.yml
keywords:
  name: 'keywords'
  content:
    default: 'cms, content manager'
description:
  name: 'description'
  content:
    default: "backbee demo website"
  lang: 'en'
robots:
  name: 'robots'
  content:
    default: ''
    select: ['', 'noindex', 'nofollow', 'noindex, nofollow']
```

BackBee loop into this configuration and display the fields and values.

So, for instance "lang" refers to the metadat "lang" which is a well know metadata for SEO.
In fact, this fields doesn't not refers to words but to the real metadata attributes.

The SEO people won't be disturbed with this form, and non SEO people won't use it.

This is why I think we should'nt try to change this behavior, which is a correct behavior / the use of this form.

What do you think ?

(Also, we can't translate this fields, mainly for the same reasons: auto-generated form)
